---
name: Verify Submodules

on:
    schedule:
        - cron: "17 5 * * *" # Daily at 05:17 UTC
    workflow_dispatch: {}

jobs:
    verify:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
              with:
                  submodules: false
                  fetch-depth: 0
            - name: Run verification script
              shell: bash
              run: |
                  bash maintenance/verify_submodules.sh
